### ISSUE TITLE
Collection of Feature Requests

### ISSUE THREAD

**Issue by Jwink3101** [hakanu/pervane#129]
I am just playing around. I do not know if this will be my tool of choice but I like it so far. And, since I know Python, I can hack it around if I need/want (though I don't know JS).

Take all of these with (a) a grain of salt, and (b) the knowledge that I understand that just because I request it, doesn't mean I feel any entitlement to it being done.

* Exclusions: I am considering using this as a web view of [notebooksapp](https://www.notebooksapp.com/) which has a lot of `.plist` files. It would be great to exclude them
* Ordering of notes within a dir from newest to oldest rather than alphabetical
* **Correct** keyboard shortcut save. CTRL+S on Windows/Linux and CMD+S on macOS
* Light Theme - I changed it in settings but the default is also light
	* Also larger font! My eyes suck
* Ability to rename notes (also, see below for another request on naming)
* Documentation/Clarification on searching: You talk a lot about `ag` in the docs but I don't have it installed and it isn't in the instructions. What's the fallback? (I saw an "issue" about `awk`. Is that what it's using?)
* Directories listed on top
* Three-column interface of directories and files.
* Automatic naming -- I *strongly* suspect you *don't* want this based on your documentation but a lot of tools name the file by the first like. It would be nice for that to be an option. Though it is harder when you do not know the name of a new note
* While I applaud *not* requiring two spaces for a new line (I think that's part of GFM? I don't recall but I hate that part of vanilla Markdown), your spell-check flags it. Spell check in general is *very* eager
* Upload images 
* (I doub't this one will happen): Ability to install or build plugins. Again, I am going from [notebooksapp](https://www.notebooksapp.com/) which has its own quirks. Can I write a plugin to translate some of them?

**Comment by metanet** [comment]
hi @Jwink3101 

Thanks for your suggestions! Note renaming, modification time based ordering, directories before files on the tree, clarification of search docs seems quite reasonable requests.

I don't quite understand "auto naming", maybe because I am not familiar with all sorts of note taking apps, other than evernote. Could you please clarify it a bit more? 

@hakanu can chime in and have a look at the other requests. 

regards,

**Comment by Jwink3101** [comment]
A lot of tools, when you ask for a new note, give you a blank note and then use the first line as both the note title and the name. (And usually strip a `#` if needed)

So for example

```markdown
# Reminders for work

Do work!
```
will be automatically names `Reminders for work.md` 

And changing that line will change the name of the file too.

I know this is how Simplenote (at least used to. I  haven't tested in a while), Notational Velocity, and Notebooksapp work.

**Comment by hakanu** [comment]
Hey @Jwink3101 cool list, good feedback. 

> Exclusions: I am considering using this as a web view of notebooksapp which has a lot of .plist files. It would be great to exclude them

You can actually do it today. Run pervane with this command:

`pervane --ignore_patterns *.plist`

But i'm sending a commit adding this. Created #130  to track.

> Ordering of notes within a dir from newest to oldest rather than alphabetical

This is a good one. Created #131 to track.

> Correct keyboard shortcut save. CTRL+S on Windows/Linux and CMD+S on macOS

This is inevitable. I didn't want to intercept with ctrl + s of saving website. Some people use. well I use myself and I don't like sites stealing my shortcuts. Don't think this will change. Alt + s was the safest option and I'm getting used to.

> Light Theme - I changed it in settings but the default is also light

Don't really understand this one.

> Also larger font! My eyes suck

Fair! Created #132 to track this.

> Ability to rename notes (also, see below for another request on naming)

This is a little bit longer to implement, created #133 to track. Not hard but multiple places to edit. 

> Documentation/Clarification on searching: You talk a lot about ag in the docs but I don't have it installed and it isn't in the instructions. What's the fallback? (I saw an "issue" about awk. Is that what it's using?)

Yes it falls back to awk. But I really recommend having ag. I even want to fallback to find which is way slower from these two.

I didn't want to bundle ag since it's another project. Not sure if there is any liability.

> Directories listed on top

This is good one. Created #134 to track this.

> Three-column interface of directories and files.

Don't think this is going to happen, happy to hear UX recommendations :) Too much screen estate. Even current sidebar occupies too much space.

> Automatic naming -- I strongly suspect you don't want this based on your documentation but a lot of tools name the file by the first like. It would be nice for that to be an option. Though it is harder when you do not know the name of a new note

Yeah as you said we take the name before creating the file. We can change the process though like directly go to note view and then an input box for the name and markdown text area for the note content. Create the file once either of it modified. Though this seems high effort, low gain to me. Feel free to challenge me. As a workaround, we can add a default name in the new note box. WDYT?

> While I applaud not requiring two spaces for a new line (I think that's part of GFM? I don't recall but I hate that part of vanilla Markdown), your spell-check flags it. Spell check in general is very eager

I don't quite get it. Spell checker highlights redundant spaces not the new line. I kinda love it because it makes my files very clean in terms of spaces. 

> Upload images

It's already here.
Either click on this button on the top right corner or drag and drop anywhere in the page to upload image to the root. Currently it's premature but works fine.

![image](https://user-images.githubusercontent.com/403473/85210729-627c2680-b33a-11ea-9d9e-887e3338a079.png)

> (I doub't this one will happen): Ability to install or build plugins. Again, I am going from notebooksapp which has its own quirks. Can I write a plugin to translate some of them?

Can not think of an architecture to do this actually. Would be great if we can enable people to modify the behavior without cloning the repo and hacking around. Though not sure how to make a pluggable environment. Any recommendation is welcome.

**Comment by Jwink3101** [comment]
Sorry for the slow reply.

### Re: `--ignore_patterns`. 

Thanks. You may want to add that and other flags to the documentation

### Re: keyboard shortcuts: 

This I guess is one of those examples of software design being opinionated. I get it 100%. I would have selected to overwrite the save since that is *much* less used. I think it breaks [the principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) since users expect regular keyboard shortcuts when editing text. They just happen to be editing in the browser. But it's your code and the beauty of writing your own code is that you get to decide!

### Re: `ag`

I don't blame you for not wanting it. But the fallback and/or dependency should be noted

### Re: naming

I think this is another one where you get to decide! I wanted to bring this alternative to your attention. I don't use Evernote but I asked my wife who does and she says she has to name new notes. Same in Joplin. I prefer the automatic but that is also because it is what I am used to. Both have pros and cons. But the ability to rename would be very good.

### Re Spell Check

This is super minor but I was pointing it out. The spell checker flags valid (though I don't like it) markdown syntax. 

### Re Uploads

I think a common theme I am seeing is discoverability of features. I am 100% **not** a UI/UX expert but some thoughts about this may be good. And maybe I just completely missed it and it was obvious. It would be good to be able to control where images go. At the very least, I would expect it to be something like `<current-dir>/uploads` or the like

### Re Plugins.

I am not sure about this either. I have a few ideas such as having them named in the config and imported but you have to be careful about security and also doing this at run time. I don't know what other tools use. It would be worth taking a look if you care. But you probably don't care....

One idea would be something like an advanced config where the user can write regexes? But again, super niche and likely not worth your time.

***

I am going to close this since you broke it out into other issues as you saw fit.
