### ISSUE TITLE
First impressions and some bugs.

### ISSUE THREAD

**Issue by vext01** [hakanu/pervane#48]
Hi,

I saw your project on lobste.rs. Looks interesting.

I installed from pip on OpenBSD. I'm using firefox and Python-3.7.

First I couldn't create nodes. No error message was shown, but the URL said:
```
http://localhost:5000/?message=failed_to_creat_md:example/test.md
```

The reason was because the storage directory didn't exist. It's fine after that. Perhaps create it if it doesn't exist, or error out?

I had a quick prod around in the editor. Some of the buttons don't seem to work. E.g. preformatted text.

File upload lets me choose a file, but I don't know where the file goes after that.

I guess you know all of this. work in progress, right?

Sorry, I won't have a lot of time to spend on this, but I thought you'd like to know anyway.

Thanks

**Comment by hakanu** [comment]
Thanks for the feedback in your limited time, really appreciated!
My TL;DR answer is all those things are work in progress. But I accept that more visibility and betterm essaging is needed at least during the start.

> First I couldn't create nodes. No error message was shown, but the URL said:

Let's track this here: https://github.com/hakanu/pervane/issues/54

> I had a quick prod around in the editor. Some of the buttons don't seem to work. E.g. preformatted text.

This is fixed with 3ae3e9236fb09fa0265787f7fcb474f75ed3064b, now releasing a new version with the fix.

> File upload lets me choose a file, but I don't know where the file goes after that.

Thought a little about the design, needed something quick for my pdf storage. However, you are right it should point out that uploads go to the root directory. Created this to track: https://github.com/hakanu/pervane/issues/55

> Sorry, I won't have a lot of time to spend on this, but I thought you'd like to know anyway.

Thanks, really appreciated!

**Comment by hakanu** [comment]
#54 is also fixed and released. Would be great if you can update: `pip install --upgrade pervane`

For #55 I will try to put some thoughts on how to make it better. Short term, probably going to add a small message saying that file is uploaded to the root directory. Hope that sounds good. Any idea is welcome.

**Comment by hakanu** [comment]
#55 is also fixed and released by redirecting to uploaded file upon successful upload or showing a visible error message on the page.

`pip install --upgrade pervane`

Thanks for the feedback!

**Comment by hakanu** [comment]
Closing the issue for now, feel free to reopen if something catches your eye.
